function [scnro, egoVehicle, actors, config] = ...
    createScenario(scenarioName)


%% ============================================
% Scenario Configuration 선택
% =============================================

switch scenarioName

    case "approach"

        config = ...
            scenario_approach();


    case "demo"

        config = ...
            scenario_demo();


    otherwise

        error( ...
            "Unknown scenario: %s", ...
            scenarioName);
end


%% ============================================
% Driving Scenario 생성
% =============================================

scnro = drivingScenario( ...
    StopTime = config.stopTime, ...
    SampleTime = config.sampleTime);


%% ============================================
% Road
% =============================================

marking = [
    laneMarking('Unmarked')
    laneMarking('Solid', ...
        Width = 0.125)
    laneMarking('Dashed', ...
        Width = 0.125, ...
        Length = 1.5, ...
        Space = 4.5)
    laneMarking('DoubleSolid', ...
        Color = [0.98 0.86 0.36], ...
        Width = 0.125)
    laneMarking('Dashed', ...
        Width = 0.125, ...
        Length = 1.5, ...
        Space = 4.5)
    laneMarking('Solid', ...
        Width = 0.125)
    laneMarking('Unmarked')
];


laneSpecification = ...
    lanespec( ...
        [3 3], ...
        Width = ...
            [0.65 3.85 3.85 3.85 3.85 0.65], ...
        Marking = marking);


road( ...
    scnro, ...
    config.roadCenters, ...
    Lanes = laneSpecification, ...
    Name = 'Road');


%% ============================================
% Ego Vehicle
%
% Ego에는 trajectory를 주지 않는다.
%
% Simulation 시작 후 Ego 상태는
% Ego Vehicle Dynamics가 관리할 예정.
% =============================================

egoVehicle = vehicle( ...
    scnro, ...
    ClassID = 1, ...
    Position = config.ego.position, ...
    Velocity = ...
        [config.ego.initialSpeed 0 0], ...
    Yaw = config.ego.yaw, ...
    Mesh = driving.scenario.carMesh, ...
    Name = 'Ego');


%% ============================================
% Actors
% =============================================

numActors = ...
    numel(config.actors);

actors = ...
    cell(numActors, 1);


for i = 1:numActors

    actorConfig = ...
        config.actors(i);


    actors{i} = vehicle( ...
        scnro, ...
        ClassID = 1, ...
        Position = actorConfig.position, ...
        Mesh = driving.scenario.carMesh, ...
        Name = actorConfig.name);


    trajectory( ...
        actors{i}, ...
        actorConfig.waypoints, ...
        actorConfig.speed, ...
        actorConfig.waitTime);
end

end