function [scnro, egoVehicle, radar] = createScenario_approach()
% createDrivingScenario Returns the drivingScenario defined in the Designer

% Generated by MATLAB(R) 26.1 (R2026a) and Automated Driving Toolbox 26.1 (R2026a).
% Generated on: 06-Aug-2026 16:48:34

% Construct a drivingScenario object.
% Stop-Time 설정
scnro = drivingScenario(StopTime = 5);

% Add all road segments
roadCenters = [-800 0 0;
               800 0 0];
marking = [laneMarking('Unmarked')
laneMarking('Solid', Width = 0.125)
laneMarking('Dashed', Width = 0.125, Length = 1.5, Space = 4.5)
laneMarking('DoubleSolid', Color = [0.98 0.86 0.36], Width = 0.125)
laneMarking('Dashed', Width = 0.125, Length = 1.5, Space = 4.5)
laneMarking('Solid', Width = 0.125)
laneMarking('Unmarked')];
laneSpecification = lanespec([3 3] , Width = [0.65 3.85 3.85 3.85 3.85 0.65], Marking = marking);
road(scnro, roadCenters, Lanes = laneSpecification, Name = 'Road');

% Add the ego vehicle
egoVehicle = vehicle(scnro, ...
     ClassID = 1, ...
     Position = [0 -5 0], ...
     Mesh = driving.scenario.carMesh, ...
     Name = 'Car');

% Add the non-ego actors
car1 = vehicle(scnro, ...
     ClassID = 1, ...
     Position = [30 -5 0], ...
     Mesh = driving.scenario.carMesh, ...
     Name = 'Car1');
waypoints = [30 -5 0;
             3 -5 0];
speed = [10;10];
waittime = [0;0];
trajectory(car1, waypoints, speed, waittime);

% Create the radar sensor
thisFolder = fileparts (mfilename('fullpath'));
addpath(fullfile(thisFolder, '..', 'radar'));
radar = createRadar(egoVehicle, scnro);

% Display the scenario
% plot(scnro,Waypoints = "on");
% while advance(scnro)
%    pause(scnro.SampleTime);
% end

